language: ruby

sudo: false

bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - jruby-19mode
  - jruby-9.1.6.0

gemfile:
  - Gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/driver_master.gemfile

matrix:
  exclude:
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/driver_master.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/driver_master.gemfile

env:
  global:
    - CI="travis"
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx1G"
  matrix:
    - MONGODB=2.4.14
    - MONGODB=2.6.11
    - MONGODB=3.0.12
    - MONGODB=3.2.11
    - MONGODB=3.4.0

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#mongoid"
